package com.fegno.callblocker.ui.theme

import androidx.compose.ui.graphics.Color

// Light scheme colors
val md_light_primary = Color(0xFF8F4C38)
val md_light_onPrimary = Color(0xFFFFFFFF)
val md_light_primaryContainer = Color(0xFFFFDBD1)
val md_light_onPrimaryContainer = Color(0xFF3A0B01)
val md_light_secondary = Color(0xFF77574E)
val md_light_onSecondary = Color(0xFFFFFFFF)
val md_light_secondaryContainer = Color(0xFFFFDBD1)
val md_light_onSecondaryContainer = Color(0xFF2C150F)
val md_light_tertiary = Color(0xFF6C5D2F)
val md_light_onTertiary = Color(0xFFFFFFFF)
val md_light_tertiaryContainer = Color(0xFFF5E1A7)
val md_light_onTertiaryContainer = Color(0xFF231B00)
val md_light_error = Color(0xFFBA1A1A)
val md_light_onError = Color(0xFFFFFFFF)
val md_light_errorContainer = Color(0xFFFFDAD6)
val md_light_onErrorContainer = Color(0xFF410002)
val md_light_background = Color(0xFFFFF8F6)
val md_light_onBackground = Color(0xFF231917)
val md_light_surface = Color(0xFFFFF8F6)
val md_light_onSurface = Color(0xFF231917)
val md_light_surfaceVariant = Color(0xFFF5DED8)
val md_light_onSurfaceVariant = Color(0xFF53433F)
val md_light_outline = Color(0xFF85736E)

// Dark scheme colors
val md_dark_primary = Color(0xFFFFB5A0)
val md_dark_onPrimary = Color(0xFF561F0F)
val md_dark_primaryContainer = Color(0xFF723523)
val md_dark_onPrimaryContainer = Color(0xFFFFDBD1)
val md_dark_secondary = Color(0xFFE7BDB2)
val md_dark_onSecondary = Color(0xFF442A22)
val md_dark_secondaryContainer = Color(0xFF5D4037)
val md_dark_onSecondaryContainer = Color(0xFFFFDBD1)
val md_dark_tertiary = Color(0xFFD8C58D)
val md_dark_onTertiary = Color(0xFF3B2F05)
val md_dark_tertiaryContainer = Color(0xFF534619)
val md_dark_onTertiaryContainer = Color(0xFFF5E1A7)
val md_dark_error = Color(0xFFFFB4AB)
val md_dark_onError = Color(0xFF690005)
val md_dark_errorContainer = Color(0xFF93000A)
val md_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_dark_background = Color(0xFF1A110F)
val md_dark_onBackground = Color(0xFFF1DFDA)
val md_dark_surface = Color(0xFF1A110F)
val md_dark_onSurface = Color(0xFFF1DFDA)
val md_dark_surfaceVariant = Color(0xFF53433F)
val md_dark_onSurfaceVariant = Color(0xFFD8C2BC)
val md_dark_outline = Color(0xFFA08C87)
